### ISSUE TITLE
Terraform execution plan fails on HTTPS-enabled influxdb servers with self-signed certificates

### ISSUE THREAD

**Issue by schahal** [terraform-providers/terraform-provider-influxdb#11]
### Terraform Version
Terraform v0.11.8

### Affected Resource(s)
provider.influxdb: v1.0.1

### Terraform Configuration Files
```hcl
provider “influxdb” {
 url      = “https://<my_host>:8443”
 username = “admin”
}
```

### Debug Output

Failure available at https://gist.github.com/schahal/4f4fd3efedd6c1bf7215ce4a3cb0c0c7

### Expected Behavior

Since this is an InfluxDB instance with HTTPS-enabled and a self-signed cert (not a valid certificate authority), the terraform execution plan should still successfully display 

### Actual Behavior

What actually happens is that when we run `terraform plan`, we get the following complaint:
```
provider.influxdb: error pinging server: Get https://<myHost>:8443/ping: x509: certificate signed by unknown authority
```
And we're unable to continue.

### Steps to Reproduce
1. Make sure you have a running InfluxDB server
2. Create a self-signed certificate (using openssl)
3. Update InfluxDB config to enable https and point the cert to path of (2)
4. Restart InfluxDB to make sure HTTPs is enabled
5. Using `.tf` config from above, run `terraform apply`

### Important Factoids
N/A

### References
N/A

**Comment by sidgod** [comment]
Closed by #12 .
