### ISSUE TITLE
[Enhancement] Support for retention policies in "influxdb_database" resource

### ISSUE THREAD

**Issue by sidgod** [terraform-providers/terraform-provider-influxdb#2]
This is enhancement request to support retention policies in influxdb_database resource. We are using InfluxDB for monitoring and for production usage we obviously need different retention policies set on different databases. In case of InfluxDB RPs (Retention Policies) are tied to InfluxDB Database so I am proposing having optional configuration in "influxdb_database" resource that'll allow us to also set RPs for that database. I've added sample configuration in following sections. Following attributes can be supported on retention_policy tag:

Name: Required attribute, Suggests a name for RP
Duration: Required attribute, Duration of RP
Replication: Optionale attribute, defaults to 1. Replication for RP.
Default: Optional attribute, defaults to false. Whether this RP is default RP or not.
ShardGroupDuration: Optional, defaults to auto determined by InfluxDB.

I've started working on getting this support coded, I've opened PL with these changes at #3 

### Terraform Version
Terraform v0.10.5

### Affected Resource(s)
- influxdb_database

### Terraform Configuration Files
```hcl
resource "influxdb_database" "testdb" {
  name = "testdb"
  retention_policies = [
    {
      name = "1day",
      duration = "1d"
    },
    {
      name = "3weeks",
      duration = "3w"
    }
  ]
}
```

**Comment by catsby** [comment]
Implemented in #3 ! Thanks for your contribution 😄
