### ISSUE TITLE
[Bug] Unapplied list of grants changes detected based on ordering

### ISSUE THREAD

**Issue by olgert** [terraform-providers/terraform-provider-influxdb#6]
After provisioning a few databases, user and grants for multiple databases, Terraform detects un-applied changes to reorder grants which makes no sense.
```
$ terraform plan
<...>
  ~ module.common.influxdb_user.grafana
      grant.0.database: "consul" => "telegraf"
      grant.1.database: "namerd" => "consul"
      grant.2.database: "telegraf" => "namerd"
      grant.4.database: "linkerd" => "nomad"
      grant.5.database: "nomad" => "linkerd"
<...>
```
### Terraform Version
```
$ terraform -v
Terraform v0.11.7
+ provider.influxdb v1.0.0
```

### Affected Resource(s)
- influxdb_user

### Terraform Configuration Files
Any configuration with a user having multiple grants to different databases

### Debug Output
https://gist.github.com/olgert/4ef79545603e6f4e806652904b8141fd

### Panic Output
N/A

### Expected Behavior
No changes to apply

### Actual Behavior
Terraform tries to apply different ordering of grants

### Steps to Reproduce
1. Have any configuration with a user having multiple grants to different databases
2. `terraform apply`
3. `terraform plan`

### Important Factoids
N/A

### References
N/A

**Comment by jareware** [comment]
Also seeing this behaviour.

**Comment by olgert** [comment]
> Looks like adding a simple sort here might fix the issue.

That's what I also though, however that would require all grants in Terraform configuration to follow same sorting order. Changing Type for grants collection from `schema.TypeList` to `schema.TypeSet` here:
https://github.com/terraform-providers/terraform-provider-influxdb/blob/05db3315d70c56da2e09ccda6772fb88688ec2a6/influxdb/resource_user.go#L35 fixes any issues with ordering, but that makes some of acceptance tests to fail. I'm currently trying to fix those failures, and hopefully I will create a PR soon.

**Comment by olgert** [comment]
Closed by mistake.

**Comment by sidgod** [comment]
@olgert Agreed, using TypeSet instead of TypeList is the right fix.

**Comment by olgert** [comment]
Please review PR #7, when you have a chance.

**Comment by jareware** [comment]
Great stuff! Any chance of making this into a release? :)
